apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingressgateway-mtls-router-executor-router-executor-unver
spec:
  exportTo:
    - .
  gateways:
    - ingressgateway-mtls-router-executor-unver
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /dab2c-router-executor/v1
        - uri:
            prefix: /healthcheck/service-healthcheck/router_executor_java_dab2c_router_executor
      route:
        - destination:
            host: router-executor-router-executor-${distrib.release.version}
            port:
              number: 8080
