/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.ru.sbrf.ufs.platform.logger.api)
    compileOnly(libs.ru.sbrf.ufs.platform.ufs.platform.healthcheck.api)
}

description = "health-check"
