kind: Deployment
apiVersion: apps/v1
metadata:
  name: @vm-agent@
  labels:
    app: @vm-agent@
    platformv.sber.ru/releaseVersion: @ufs.release@
    platformv.sber.ru/config-fp-name: @vm-agent@
    platformv.sber.ru/fullReleaseVersion: @schemas.version@
spec:
  selector:
    matchLabels:
      platformv.sber.ru/config-fp-name: @vm-agent@
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: ${@config-fp-name1@.ctr.deployment.spec.strategy.rollingUpdate.maxSurge}
      maxUnavailable: ${@config-fp-name1@.ctr.deployment.spec.strategy.rollingUpdate.maxUnavailable}
    type: RollingUpdate
  triggers:
    - type: ConfigChange
  template:
    metadata:
      labels:
        distrib-version: ${jenkins_env.fp_artifact_version}
        jenkinsDeployId: ${jenkinsDeployId}
        platformv.sber.ru/releaseVersion: @ufs.release@
        platformv.sber.ru/config-fp-name: @vm-agent@
        platformv.sber.ru/fullReleaseVersion: @schemas.version@
        secman-injector: enabled
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: ${@config-fp-name1@.ctr.deployment.metadata.annotations.sidecar.istio.io.proxyCPU}
        sidecar.istio.io/proxyMemory: ${@config-fp-name1@.ctr.deployment.metadata.annotations.sidecar.istio.io.proxyMemory}
        sidecar.istio.io/proxyCPULimit: ${@config-fp-name1@.ctr.deployment.metadata.annotations.sidecar.istio.io.proxyCPULimit}
        sidecar.istio.io/proxyMemoryLimit: ${@config-fp-name1@.ctr.deployment.metadata.annotations.sidecar.istio.io.proxyMemoryLimit}
    spec:
      serviceAccountName: ${vmAgent.ctr.deployment.spec.serviceAccount}
      securityContext:
        fsGroup: 101337
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - @vm-agent@
                topologyKey: topology.kubernetes.io/hostname
      volumes:
        - name: vm-agent
          configMap:
            name: vm-agent
            defaultMode: 256
        - name: vm-agent-remotewrite-data
          emptyDir: {}
      containers:
        - name: vm-agent
          image: ${registry}/CIXXXXXXX/CIXXXXXXX/victoriametrics/vmagent:v1.108.0@sha256:232604220c39e4bbb63f8dc3e240e22e1a92526ad17590f43ed9c7fd5d24b909
          args:
            - '-httpListenAddr=:8429'
            - '--promscrape.config=/vault/vm-agent/scrape.yaml'
            - '--remoteWrite.tmpDataPath=/tmp/vm-agent-remotewrite-data'
            - '--remoteWrite.tlsInsecureSkipVerify'
            - '--remoteWrite.url=http://${global.monitoring.store.host}:${global.monitoring.store.port}/api/v1/write'
            - '--remoteWrite.showURL=true'
            - '--promscrape.maxScrapeSize=100MB'
            - '--loggerLevel=INFO'
          ports:
            - name: vmagent
              containerPort: 8429
          resources:
            limits:
              cpu: ${vmAgent.ctr.deployment.spec.template.spec.containers.vmAgent.resources.limits.cpu}
              memory: ${vmAgent.ctr.deployment.spec.template.spec.containers.vmAgent.resources.limits.memory}
            requests:
              cpu: ${vmAgent.ctr.deployment.spec.template.spec.containers.vmAgent.resources.requests.cpu}
              memory: ${vmAgent.ctr.deployment.spec.template.spec.containers.vmAgent.resources.requests.memory}
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1003600337
            runAsGroup: 1003600337
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: vm-agent
              mountPath: /vault/vm-agent/
            - name: vm-agent-remotewrite-data
              mountPath: /tmp/vm-agent-remotewrite-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ${global.ufs.secrets.imagePullSecrets}
      schedulerName: default-scheduler
