org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx1G -XX:MaxMetaspaceSize=1g \
                    -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=./cacerts -Djavax.net.ssl.trustStorePassword=changeit
org.gradle.caching=false
org.gradle.daemon=true
kotlin.code.style=official
kapt.use.worker.api=true
kapt.incremental.apt=true
kapt.include.compile.classpath=false

# Project properties (equivalent to Maven properties)
server.host=localhost
server.port=8080
server.context.version=v1
server.context.path=executor
kafka.host=localhost
kafka.port=29092

fpi-name=executor
config-fp-name1=executor
vm-agent=vm-agent
vm-agent-du=vm-agent
subsystemCode=EXECUTOR
subsystemCode.lowercase=executor
deploymentUnit1=executor
tenantCode=DAB2C
app.support.description=DA B2C Executor service
app-conf-item.uppercase=CI12008538
app-conf-item.lowercase=CI12008538
as-conf-item.uppercase=CI07909419
as-conf-item.lowercase=CI07909419

ufs.release=R4.3
ufs.release.postfix=4.3
schemas.version=R4.3.1
ufs.channel=ALL
ufs.api.version=1.0
project.version=1.0.0
distrib.version=none

audit-ci-name=CI12008538_integration_service_v1
audit-metamodel-topic=CI07909419.CI07909419-metamodel
audit-crit-event-topic=CI07909419.CI12008538-integration-service
audit-uncrit-event-topic=CI07909419.CI12008538-integration-service

skip.all.checks=false
build.distr = true