org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx1G -XX:MaxMetaspaceSize=1g \
                    -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=./cacerts -Djavax.net.ssl.trustStorePassword=changeit org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
kotlin.code.style=official
kapt.use.worker.api=true
kapt.incremental.apt=true
kapt.include.compile.classpath=false

# Project properties (equivalent to Maven properties)
server.host=localhost
server.port=8080
server.context.version=v1
server.context.path1=dab2c-router-executor/v1

# Skip checks flag (use -PskipAllChecks=true to skip)
skipAllChecks=false
build-distr = true