<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
    <artifactId>executor</artifactId>
    <version>${revision}</version>
    <name>executor</name>
    <packaging>pom</packaging>

    <modules>
        <module>executor-application</module>
        <module>executor-shared</module>
    </modules>

    <properties>
        <!-- Версии зависимостей -->
        <apache.common-text.version>1.10.0</apache.common-text.version>
        <java.version>21</java.version>
        <hamcrest.version>1.3</hamcrest.version>
        <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
        <junit.bom.version>5.10.0</junit.bom.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <bytebuddy.version>1.14.18</bytebuddy.version>
        <assertj.version>3.21.0</assertj.version>
        <ufs.platform.bom.version>10.4.2.50</ufs.platform.bom.version>
        <ufs.uko-session-stub.version>2.0.6</ufs.uko-session-stub.version>
        <ufs.workflow-lib.version>2.3.0</ufs.workflow-lib.version>
        <jaxb.version>3.0.2</jaxb.version>
        <mockk.version>1.12.3</mockk.version>
        <wiremock.version>3.3.1</wiremock.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <resilience4j.version>1.7.0</resilience4j.version>
        <spotbugs.annotations.version>4.8.5</spotbugs.annotations.version>
        <json-path.annotations.version>2.9.0</json-path.annotations.version>

        <!-- Версии плагинов  -->
        <plugin.compiler.version>3.8.1</plugin.compiler.version>
        <plugin.checkstyle.version>3.1.2</plugin.checkstyle.version>
        <checkstyle.version>10.7.0</checkstyle.version>
        <plugin.dependencies.version>3.7.0</plugin.dependencies.version>
        <plugin.exec.version>3.0.0</plugin.exec.version>
        <plugin.jacoco.version>0.8.12</plugin.jacoco.version>
        <plugin.resources.version>3.2.0</plugin.resources.version>
        <plugin.sonarqube.version>3.7.0.1746</plugin.sonarqube.version>
        <plugin.spotbugs.version>4.8.5.0</plugin.spotbugs.version>
        <plugin.spotbugs.sbcontrib.version>7.6.4</plugin.spotbugs.sbcontrib.version>
        <plugin.spotbugs.findsecbugs.version>1.13.0</plugin.spotbugs.findsecbugs.version>
        <plugin.springboot.version>2.7.18</plugin.springboot.version>
        <plugin.sup.version>1.3.4</plugin.sup.version>
        <plugin.surefire.version>3.0.0-M5</plugin.surefire.version>
        <plugin.versions.version>2.16.0</plugin.versions.version>
        <plugin.maven-jar-plugin.version>3.1.0</plugin.maven-jar-plugin.version>
        <plugin.assembly.version>3.7.1</plugin.assembly.version>
        <plugin.detekt.version>1.23.7</plugin.detekt.version>
        <plugin.zero-compress-plugin.version>0.9.0</plugin.zero-compress-plugin.version>
        <plugin.build-helper.version>3.6.0</plugin.build-helper.version>

        <detekt.version>1.23.6</detekt.version>

        <!-- Информация для SpringBoot -->
        <server.host>localhost</server.host>
        <server.port>8080</server.port>
        <server.context.version>v1</server.context.version>
        <server.context.path1>dab2c-router-executor/${server.context.version}</server.context.path1>

        <!--
        Данные для env.properties и конфигов
        Справка: https://confluence.sberbank.ru/pages/viewpage.action?pageId=13814498994
        -->
        <fpi-name>router-executor</fpi-name>
        <config-fp-name1>${fpi-name}-router-executor</config-fp-name1>
        <subsystemCode>ROUTER_EXECUTOR_JAVA_DAB2C</subsystemCode>
        <subsystemCode.lowercase>router_executor_java_dab2c</subsystemCode.lowercase>
        <deploymentUnit1>router_executor_java_dab2c_router_executor</deploymentUnit1>
        <app.support.description>ROUTER_EXECUTOR_JAVA_DAB2C</app.support.description>
        <app-conf-item.uppercase>CI12008538</app-conf-item.uppercase>
        <app-conf-item.lowercase>ci12008538</app-conf-item.lowercase>
        <as-conf-item.uppercase>CI07909419</as-conf-item.uppercase>
        <as-conf-item.lowercase>ci07909419</as-conf-item.lowercase>

        <ufs.release>R4.2</ufs.release>
        <ufs.release.postfix>4.2</ufs.release.postfix>
        <schemas.version>R4.2.4</schemas.version>
        <ufs.channel>ALL</ufs.channel>
        <ufs.api.version>1.0</ufs.api.version>
        <FP_VERSION>${ufs.release}-${project.version}</FP_VERSION>

        <!-- Настройки SonarQube -->
        <sonar.host.url>https://sbt-sonarqube.sigma.sbrf.ru</sonar.host.url>
        <sonar.login>sqp_85bd535d881cea6171d59e505ab60c506cd4a505</sonar.login>
        <sonar.ws.timeout>300</sonar.ws.timeout>
        <!-- Эти же exclude-ы используются в конфигурации плагина Jacoco -->
        <sonar.coverage.exclusions>
            **/dto/**,
            **/factory/**,
            **/pojo/**,
            **/*Exception.*,
            **/config/**,
            **/*Configuration.*,
            **/model/**,
            **/DefaultAutoConfigurationExcludeProvider.kt,
            **/SpykBeanConfig.kt,
            **/HttpResponseExt.kt,
            **/testutils/**,
            **/*Stub.kt,
            **/*EntryPoint.kt,
            **/*Exception*.kt,
            **/*ServiceHostProvider.kt
        </sonar.coverage.exclusions>
        <sonar.coverage.jacoco.xmlReportPaths>${project.build.directory}/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.java.checkstyle.reportPaths>${project.build.directory}/checkstyle-result.xml</sonar.java.checkstyle.reportPaths>
        <sonar.kotlin.detekt.reportPaths>${project.build.directory}/detekt/detekt.xml</sonar.kotlin.detekt.reportPaths>
        <sonar.java.spotbugs.reportPaths>${project.build.directory}/spotbugsXml.xml</sonar.java.spotbugs.reportPaths>
        <sonar.surefire.reportsPath>${project.build.directory}/surefire-reports</sonar.surefire.reportsPath>
        <sonar.java.source>${java.version}</sonar.java.source>
        <sonar.java.target>${java.version}</sonar.java.target>
        <sonar.sources>src/main</sonar.sources>

        <!-- Прочие свойства -->
        <skip.all.checks>false</skip.all.checks>

        <!-- Кодировка -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <!-- kotlin -->
        <kotlin.version>2.1.0</kotlin.version>

        <detekt.config>./config/detekt/detekt_config.yml</detekt.config>
    </properties>

    <build>
        <extensions>
            <extension>
                <groupId>org.apache.maven.extensions</groupId>
                <artifactId>maven-build-cache-extension</artifactId>
                <version>1.2.0</version>
            </extension>
        </extensions>
        <pluginManagement>
            <plugins>
                <!-- Компиляция, сборка артефактов, прогон тестов -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${plugin.compiler.version}</version>
                </plugin>
                <plugin>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <version>${kotlin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${plugin.maven-jar-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${plugin.resources.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${plugin.versions.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${plugin.surefire.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${plugin.dependencies.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${plugin.exec.version}</version>
                </plugin>
                <plugin>
                    <groupId>ru.sbrf.ufs.zero-compress-plugin</groupId>
                    <artifactId>maven-plugin</artifactId>
                    <version>${plugin.zero-compress-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${plugin.springboot.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${plugin.assembly.version}</version>
                </plugin>
                <plugin>
                    <groupId>ru.sbrf.ufs.tool</groupId>
                    <artifactId>ufs-artifact-maven-plugin</artifactId>
                    <version>${plugin.sup.version}</version>
                </plugin>

                <!-- Статический анализ -->
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${plugin.spotbugs.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.commons</groupId>
                            <artifactId>commons-text</artifactId>
                            <version>${apache.common-text.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${plugin.jacoco.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${plugin.sonarqube.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.github.ozsie</groupId>
                    <artifactId>detekt-maven-plugin</artifactId>
                    <version>${plugin.detekt.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${plugin.build-helper.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <fileNameFiltering>true</fileNameFiltering>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.github.ozsie</groupId>
                <artifactId>detekt-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <report>xml:${project.build.directory}/detekt/detekt.xml</report>
                            <skip>${skip.all.checks}</skip>
                            <config>config/detekt/detekt_config.yml</config>
                            <excludes>**/resources/**</excludes>
                            <autoCorrect>true</autoCorrect>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>io.gitlab.arturbosch.detekt</groupId>
                        <artifactId>detekt-formatting</artifactId>
                        <version>${detekt.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <configuration>
                    <effort>Max</effort>
                    <excludeFilterFile>config/spotbugs/excludeFilters.xml</excludeFilterFile>
                    <includeTests>true</includeTests>
                    <threshold>Low</threshold>
                    <xmlOutput>true</xmlOutput>
                    <plugins>
                        <plugin>
                            <groupId>com.mebigfatguy.sb-contrib</groupId>
                            <artifactId>sb-contrib</artifactId>
                            <version>${plugin.spotbugs.sbcontrib.version}</version>
                        </plugin>
                        <plugin>
                            <groupId>com.h3xstream.findsecbugs</groupId>
                            <artifactId>findsecbugs-plugin</artifactId>
                            <version>${plugin.spotbugs.findsecbugs.version}</version>
                        </plugin>
                    </plugins>
                    <skip>${skip.all.checks}</skip>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>verify</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>${sonar.coverage.exclusions}</exclude>
                    </excludes>
                    <skip>${skip.all.checks}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>agent-for-ut</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>sonar</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sonar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>kapt</id>
                        <goals>
                            <goal>kapt</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/main/kotlin</sourceDir>
                            </sourceDirs>
                            <annotationProcessorPaths>
                                <annotationProcessorPath>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${mapstruct.version}</version>
                                </annotationProcessorPath>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/target/generated-sources/kapt/compile</sourceDir>
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/test/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>

                <configuration>
                    <compilerPlugins>
                        <plugin>all-open</plugin>
                        <plugin>spring</plugin>
                        <plugin>no-arg</plugin>
                        <plugin>jpa</plugin>
                    </compilerPlugins>
                    <args>
                        <arg>-Xjvm-default=all-compatibility</arg>
                    </args>
                </configuration>

                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-noarg</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${mapstruct.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>java-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>java-test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <!-- Liquibase -->
            <dependency>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-core</artifactId>
                <version>${liquibase.version}</version>
            </dependency>
            <dependency>
                <groupId>sbrf.liquibase</groupId>
                <artifactId>liquibase-sqlplus</artifactId>
                <version>${liquibase.version}</version>
            </dependency>
            <dependency>
                <groupId>com.oracle</groupId>
                <artifactId>ojdbc8</artifactId>
                <version>${oracle.jdbc.version}</version>
            </dependency>

            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>${jaxb.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-core</artifactId>
                <version>${jaxb.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <!-- Тестирование -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.mockk</groupId>
                <artifactId>mockk-jvm</artifactId>
                <version>${mockk.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.mockk</groupId>
                <artifactId>mockk</artifactId>
                <version>${mockk.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.wiremock</groupId>
                <artifactId>wiremock-standalone</artifactId>
                <version>${wiremock.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- Byte buddy -->
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy</artifactId>
                <version>${bytebuddy.version}</version>
            </dependency>

            <!-- kotlin -->
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Платформа -->
            <dependency>
                <groupId>ru.sbrf.ufs.platform</groupId>
                <artifactId>ufs-platform-bom</artifactId>
                <version>${ufs.platform.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>2.17.1</version>
            </dependency>

            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>2.2</version>
            </dependency>

            <!-- spotbugs -->
            <dependency>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-annotations</artifactId>
                <version>${spotbugs.annotations.version}</version>
            </dependency>

            <!-- JSON Path support -->
            <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path</artifactId>
                <version>${json-path.annotations.version}</version>
            </dependency>

            <!--  resilience4j -->
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-circuitbreaker</artifactId>
                <version>${resilience4j.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-retry</artifactId>
                <version>${resilience4j.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-bulkhead</artifactId>
                <version>${resilience4j.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-ratelimiter</artifactId>
                <version>${resilience4j.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-spring-boot2</artifactId>
                <version>${resilience4j.version}</version>
            </dependency>

            <!-- submodules -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>executor-application</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>executor-shared</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- Exported modules -->

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>router-executor</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>cbul-integration</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- FIXME: Remove after CBUL 13 release appear in platform BOM -->
            <dependency>
                <groupId>ru.sbrf.cbul</groupId>
                <artifactId>cbul-client-spring-boot-starter</artifactId>
                <version>1.13.2.dev</version>
            </dependency>
            <dependency>
                <groupId>ru.sbrf.cbul</groupId>
                <artifactId>cbul-client-impl</artifactId>
                <version>13.0.2.dev</version> <!-- Match starter's expectation -->
            </dependency>
            <dependency>
                <groupId>ru.sbrf.cbul</groupId>
                <artifactId>cbul-client-api</artifactId>
                <version>13.0.2.dev</version>
            </dependency>
            <dependency>
                <groupId>ru.sbrf.cbul</groupId>
                <artifactId>cbul-client-api-dto</artifactId>
                <version>13.0.2.dev</version>
            </dependency>
            <dependency>
                <groupId>ru.sbrf.cbul</groupId>
                <artifactId>cbul-core</artifactId>
                <version>13.0.2.dev</version>
            </dependency>
            <!-- END FIXME -->

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>circuit-breaker</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>health-check</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>monitoring</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>commons</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>test-utils</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>logging</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>rest-object-mapper</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>annotations</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>concurrent</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>system-env</artifactId>
                <version>${revision}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>${javax.annotation-api.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </dependency>

        <!-- Тестирование -->
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
            <version>${assertj.version}</version>
        </dependency>

        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- kotlin -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-config-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-config-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-api</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-json-mapper</artifactId>
        </dependency>

    </dependencies>

</project>
