/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "executor"
include(":executor-application:configs")
include(":executor-application:deployments")
include(":executor-application:deployments:router-executor")
include(":executor-shared:health-check")
include(":executor-shared:monitoring")
include(":executor-shared:executor-application")
include(":executor-shared:executor-shared")
include(":executor-shared:concurrent")
include(":executor-shared:test-utils")
include(":executor-shared:cbul-integration")
include(":executor-shared:system-env")
include(":executor-shared:circuit-breaker")
include(":executor-shared:annotations")
include(":executor-shared:rest-object-mapper")
include(":executor-shared:commons")
include(":executor-shared:logging")

pluginManagement {
    repositories {
        val nexusUsername = System.getProperty("gradle.wrapperUser")
        val nexusPassword = System.getProperty("gradle.wrapperPassword")
        maven {
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
            url = uri("https://nexus-ci.delta.sbrf.ru/repository/public/")
        }
        maven {
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
            url = uri("https://nexus-ci.delta.sbrf.ru/repository/maven-lib-int/")
        }
    }
    plugins {
        id("ru.sbrf.ufs.confirmation.sup") version "1.0.7"
    }
}
