/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "executor"
include(":health-check")
include(":monitoring")
include(":configs")
include(":executor-application")
include(":router-executor")
include(":executor-shared")
include(":concurrent")
include(":test-utils")
include(":cbul-integration")
include(":system-env")
include(":circuit-breaker")
include(":deployments")
include(":annotations")
include(":rest-object-mapper")
include(":commons")
include(":logging")
project(":health-check").projectDir = file("executor-shared/health-check")
project(":monitoring").projectDir = file("executor-shared/monitoring")
project(":configs").projectDir = file("executor-application/configs")
project(":router-executor").projectDir = file("executor-application/deployments/router-executor")
project(":concurrent").projectDir = file("executor-shared/concurrent")
project(":test-utils").projectDir = file("executor-shared/test-utils")
project(":cbul-integration").projectDir = file("executor-shared/cbul-integration")
project(":system-env").projectDir = file("executor-shared/system-env")
project(":circuit-breaker").projectDir = file("executor-shared/circuit-breaker")
project(":deployments").projectDir = file("executor-application/deployments")
project(":annotations").projectDir = file("executor-shared/annotations")
project(":rest-object-mapper").projectDir = file("executor-shared/rest-object-mapper")
project(":commons").projectDir = file("executor-shared/commons")
project(":logging").projectDir = file("executor-shared/logging")

pluginManagement {
    repositories {
        val nexusUsername = System.getProperty("gradle.wrapperUser")
        val nexusPassword = System.getProperty("gradle.wrapperPassword")
        maven {
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
            url = uri("https://nexus-ci.delta.sbrf.ru/repository/public/")
        }
        maven {
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
            url = uri("https://nexus-ci.delta.sbrf.ru/repository/maven-lib-int/")
        }
    }
    plugins {
        id("ru.sbrf.ufs.confirmation.sup") version "1.0.7"
    }
}
