apiVersion: v1
kind: Service
metadata:
  labels:
    app: @config-fp-name1@
  name: @config-fp-name1@-${distrib.release.version}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    platformv.sber.ru/config-fp-name: @config-fp-name1@
  type: ClusterIP
