apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressgateway-mtls-@fpi-name@-unver
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/load-balance: 'round_robin'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '180'
  labels:
    app: istio-ingressgateway-@fpi-name@-unver
    chart: gateways
    heritage: Tiller
    istio: ingressgateway-@fpi-name@-unver
    release: istio
    sectorId: '{{ TENANT_CODE }}'
spec:
  ingressClassName: nginx
  rules:
    - host: ${@fpi-name@.ctr.istio.ingress.route.spec.host.@fpi-name@.appFQDN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingressgateway-@fpi-name@-unver
                port:
                  name: https-11443