<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
        <artifactId>executor-shared</artifactId>
        <version>${revision}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>commons</artifactId>
    <packaging>jar</packaging>
    <version>${revision}</version>

    <dependencies>

        <!-- Logger -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>


        <!-- JSON Path support -->
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
        </dependency>

        <!-- Spring context -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Spring WebMVC -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Platform JSON Mapper -->
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-json-mapper</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>

        <dependency>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <groupId>com.fasterxml.jackson.datatype</groupId>
        </dependency>

        <!-- Spring boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Platform core -->
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>ufs-platform-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Платформенное Ядро: Окружение -->
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>environment-spring-boot-starter</artifactId>
        </dependency>

        <!-- Cbreaker -->
        <dependency>
            <groupId>ru.sbrf.ufs.cbreaker</groupId>
            <artifactId>circuit-breaker-api</artifactId>
        </dependency>

        <!-- Тестирование -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Logger -->
        <dependency>
            <groupId>ru.sbrf.ufs.platform</groupId>
            <artifactId>logger-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>test-utils</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>rest-object-mapper</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.zip</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.zip</include>
                </includes>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.zip</exclude>
                </excludes>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <includes>
                    <include>**/*.zip</include>
                </includes>
            </testResource>
        </testResources>
    </build>

</project>
