apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egressgateway-mtls-router-executor-iagmm-unver
spec:
  exportTo:
    - .
  hosts:
    - ${router-executor.ctr.istio.egress.se.http.iag-mm.host}
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: ${router-executor.ctr.istio.egress.common.internal-port}
      protocol: HTTP
    - name: https-iagmm
      number: ${router-executor.ctr.istio.egress.se.http.iag-mm.port}
      protocol: HTTPS
  resolution: DNS