apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-mtls-router-executor-iagmm-unver
spec:
  exportTo:
    - .
  host: ${router-executor.ctr.istio.egress.se.http.iag-mm.host}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: ${router-executor.ctr.istio.egress.se.http.iag-mm.port}
        tls:
          caCertificates: /vault/secrets/ca-chain.pem
          clientCertificate: /vault/secrets/client-cert.pem
          privateKey: /vault/secrets/client-cert.key
          mode: MUTUAL
          sni: ${router-executor.ctr.istio.egress.se.http.iag-mm.host}
  workloadSelector:
    matchLabels:
      app: istio-egressgateway-router-executor-unver
      istio: egressgateway-router-executor-unver
