apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egressgateway-mtls-router-executor-unver
spec:
  selector:
    istio: egressgateway-router-executor-unver    # Селектор, который определяет каким gateway'ем будет обрабатываться этот конфиг;
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: ${router-executor.ose.istio.egress.common.internal-port}
        protocol: HTTP
