apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egressgateway-tcp-router-executor-unver
spec:
  exportTo:
    - .
  hosts:
    - ignored
  location: MESH_EXTERNAL
  ports:
    # Порт, нужный всему набору Журналирование-Мониторинг-Аудит
    - name: tcp-kafka
      number: ${router-executor.ose.istio.egress.se.tcp.kafkaPort.number}
      protocol: TCP
  resolution: NONE
