logger.test.mode=true
logger.local.enabled=true
logger.local.level=INFO
logger.remote.enabled=true
logger.remote.level=INFO
logger.name.level=ru.sbrf.ufs.monitoring.session.SessionImpl:INFO,\
  ru.sbrf.ufs.integration.module.transport.jms.AbstractJmsTransport:INFO,\
  ru.sbrf.ufs.healthcheck:WARN,\
  ru.sbrf.ufs.platform.config.v3.logging.RequestResultPrinter:WARN,\
  ru.sbrf.ufs.cbreaker:WARN
logger.local.stdout.appender.enabled=true
logger.erib.enabled=true
