[versions]
# Kotlin and Java
kotlin = "2.1.0"
java = "21"

#BOMs
ufs-platform-bom = "10.4.2.50"
junit = "5.10.0"

# Spring Boot and related
spring-boot = "3.5.5"
spring-dependency-management = "1.1.7"

# Kotlinx
kotlinx-serialization = "1.7.3"
kotlinx-coroutines = "1.9.0"
kotlinx-datetime = "0.6.1"

# Logging
kotlin-logging = "5.1.0"

# Other libraries
javax-annotation-api = "1.3.2"

# Testing
mockk = "1.14.5"

slf4j = "2.0.16"
resilience4j = "1.7.0"
assertj = "3.24.2"

[libraries]
#platform BOM
ufs-platform-bom = { module = "ru.sbrf.ufs.platform:ufs-platform-bom", version.ref = "ufs-platform-bom" }

# Spring Boot
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# Kotlinx
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# resilience4j
resilience4j-circuitbreaker = { module = "io.github.resilience4j:resilience4j-circuitbreaker", version.ref = "resilience4j"}

# Logging
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# Validation
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }

apache-httpclient = { module = "org.apache.httpcomponents:httpclient" }
apache-httpcore = { module = "org.apache.httpcomponents:httpcore" }

# Gradle plugins (for buildSrc)
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }

slf4j-log4j12 = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }
hamcrest-core = { module = "org.hamcrest:hamcrest-core" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

# Spring Core libraries (if not already defined)
spring-core = { module = "org.springframework:spring-core" }
spring-context = { module = "org.springframework:spring-context" }
spring-beans = { module = "org.springframework:spring-beans" }
spring-test = { module = "org.springframework:spring-test" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test" }
spring-boot-test-autoconfigure = { module = "org.springframework.boot:spring-boot-test-autoconfigure" }

ufs-platform-config-api = { module = "ru.sbrf.ufs.platform:ufs-platform-config-api" }
ufs-platform-config-core = { module = "ru.sbrf.ufs.platform:ufs-platform-config-core" }
ufs-platform-api = { module = "ru.sbrf.ufs.platform:ufs-platform-api" }
ufs-platform-json-mapper = { module = "ru.sbrf.ufs.platform:ufs-platform-json-mapper" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine" }

#Monitoring
monitoring-starter = { module = "ru.sbrf.ufs.monitoring.spring-boot:monitoring-spring-boot-starter" }
monitoring-api = { module = "ru.sbrf.ufs.platform:ufs-platform-monitoring-api" }
monitoring-core = { module = "ru.sbrf.ufs.monitoring:monitoring-core" }
monitoring-models = { module = "ru.sbrf.ufs.monitoring:monitoring-models" }
monitoring-module = { module = "ru.sbrf.ufs.monitoring:monitoring-module" }
monitoring-session = { module = "ru.sbrf.ufs.monitoring:monitoring-session" }
monitoring-spring-boot-autoconfigure = { module = "ru.sbrf.ufs.monitoring.spring-boot:monitoring-spring-boot-autoconfigure" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }

#Logging
ufs-logger-springboot-starter = { module = "ru.sbrf.ufs.platform:logger-springboot-starter" }
ufs-logger-api = { module = "ru.sbrf.ufs.platform:logger-api" }

#Healthcheck
ufs-platform-healthcheck-api = { module = "ru.sbrf.ufs.platform:ufs-platform-healthcheck-api" }
ufs-healthcheck-spring-boot-starter = { module = "ru.sbrf.ufs.healthcheck:ufs-healthcheck-spring-boot-starter" }

[bundles]
# Spring Boot Web and Core

ufs-core = [
    "ufs-platform-config-api",
    "ufs-platform-config-core",
    "ufs-platform-api",
    "ufs-platform-json-mapper"
]

ufs-logging = [
    "ufs-logger-springboot-starter",
    "ufs-logger-api"
]

ufs-monitoring = [
    "monitoring-starter",
    "monitoring-api",
    "monitoring-core",
    "monitoring-models",
    "monitoring-module",
    "monitoring-session",
    "monitoring-spring-boot-autoconfigure",
    "monitoring-spring-boot-autoconfigure",
    "spring-boot-starter-actuator"
]

ufs-healthcheck = [
    "ufs-platform-healthcheck-api",
    "ufs-healthcheck-spring-boot-starter"
]

spring-boot-web = [
    "spring-boot-starter-webflux",
    "spring-boot-starter-aop"
]

# Jackson
jackson = [
    "jackson-module-kotlin",
    "jackson-annotations",
    "jackson-datatype-jsr310"
]

# Kotlinx
kotlinx = [
    "kotlinx-serialization-json",
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-reactor",
    "kotlinx-datetime"
]

# Testing
testing = [
    "mockk",
    "spring-boot-starter-test",
    "kotlin-test-junit5",
    "junit-bom",
    "junit-platform-launcher",
    "junit-jupiter",
    "junit-jupiter-api",
    "junit-jupiter-params",
    "junit-jupiter-engine",
    "junit-platform-commons",
    "junit-platform-engine",
    "spring-test",
    "spring-boot-test",
    "spring-boot-test-autoconfigure",
    "hamcrest-core",
    "assertj-core"
]

spring-core = [
    "spring-core",
    "spring-context",
    "spring-beans"
]

httpcomponents = ["apache-httpclient", "apache-httpcore"]

[plugins]
# Kotlin plugins
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Spring Boot plugins
spring-boot = { id = "org.springframework.boot" }
