spring:
  main:
    web-application-type: reactive

management:
  endpoint:
    health:
      probes:
        enabled: true
    quartz:
      enabled: false
  health:
    jms:
      enabled: false

logging:
  level:
    root: INFO

ufs:
  platform:
    # Платформенное Ядро
    environment:
      product:
        subsystem: ROUTER_EXECUTOR_JAVA_DAB2C
        channel: ALL
        deploymentUnit: router_executor_java_dab2c_router_executor
        distrib_version: D-01.000.00
        release: R4.3
    # СУП. См. также класс SupAdditionalConfiguration — в нём создаётся бин для СУП Data.
    config:
      deploymentUnit: router_executor_java_dab2c_router_executor
    # Content Broker
    cbro:
      errors:
        useSberCmsErrorService: true
      hints:
        useSberCmsHintsService: true

  # Мониторинг
  monitoring:
    client:
      enable: true
      channel: ALL
      distributiveVersion: D-01.000.00
      version: D-01.000.00
      subsystem: ROUTER_EXECUTOR_JAVA_DAB2C
      title: ROUTER_EXECUTOR_JAVA_DAB2C
      thread-name-prefix: "ufs-monitoring-ROUTER_EXECUTOR_JAVA_DAB2C-thread"
      unit: router_executor_java_dab2c_router_executor

  # Healthcheck
  healthcheck:
    stub-agent-enabled: true
    groups:
      readiness: "ru.sbrf.ufs.dab2c.core.executor.shared.healthcheck.ApplicationHealthCheck"

  # История операций
  operation-history:
    request-services:
      kangarooHistoryService:
        entity-class: "ru.sbrf.ufs.dab2c.core.history.dto.HistoryKangarooProperties"

  # САЗ
  task-scheduler:
    installation:
      type: BLOCK

  # Интеграционный модуль
  integration:
    module:
      autostart: true
    adapter:
      channel: ALL
      subsystem-code: ROUTER_EXECUTOR_JAVA_DAB2C

  # Справочники
  dictionary:
    client:
      channel: ALL
      subsystem: ROUTER_EXECUTOR_JAVA_DAB2C

  # Техперерывы
  tech-break:
    client:
      enable-adapter: true

sds:
  platformv:
    monitoring:
      targets: "pvm"

seans:
  enable: true
  optional-data-enable: true
