server:
  address: localhost
  port: 8080

stand:
  type: TEST

ufs:
  platform:
    # СУП
    config:
      directory: "classpath:/mock/sup"
      agent:
        disabled: true
    # Launcher
    launcherstub:
      enabled: true
      enable-rest: true

  # ССД
  sds:
    client:
      mode: LOCAL
      http:
        integration-enabled: true

  # Журналирование
  logger:
    client:
      mode: FRONTEND_LOCAL
      providerFileName: "/mock/logger/logger.properties"

  # HotReload
  hotreload:
    enable: false

  # Мониторинг
  # См. также pom.xml с включением stubMode
  monitoring:
    client:
      period: 20s
    kafka:
      enabled: false
      ssl: false

  # Аудит
  audit:
    client:
      stub: true
      useQuota: false

  # Blockrouter
  blockrouter:
    source: local
    mocksPath: 'mock/standin/standin-mock-stub.json'

  # Launcher
  launcher:
    client:
      mode: REMOTE

  # История операция
  operation-history:
    request-services:
      kangarooHistoryService:
        stub-helper-id: "requestStub"
        ref-to-initializer-id: "kangarooEntityStubInitializer"

  # Compliance (БИПО)
  bioc:
    client:
      mode: local
      stubFile: "mock/compliance/mock-response.json"

  # Компонента Фродмониторинга
  fraudmon:
    client:
      mode: local

  # Профиль ФЛ
  idpersonremote:
    client:
      mode: local

  # САЗ
  task-scheduler:
    registrator:
      client:
        mode: LOCAL
        enabled: true
    executor:
      client:
        mode: LOCAL
        enabled: true

  # Интеграционный модуль
  integration:
    module:
      executorService:
        poolSize: 5
      kafka:
        consumerFactories:
          - name: kafka/factory/CONSUMER_FACTORY_COMMON
            properties:
              "[bootstrap.servers]": "tcp://localhost:29092"

  # Техперерывы
  tech-break:
    client:
      mode: local
      local-source: "classpath:/mock/cbreaker/client-answers.json"

  # Toggler
  feature-toggle:
    client:
      mode: LOCAL
      mock-features-path: mock/toggler/toggler-privileges-mock.json
      mock-authorization-data:
        # Путь до файла-заглушки привилегий авторизации (ранее использовавшийся ufs.security.client.local-file-privileges-path)
        local-file-privileges-path: mock/toggler/authorization-privileges-mock.json

  # Справочники
  dictionary:
    client:
      local-source: true
      source-files:
        - "mock/dictionary/dictionary1.json"
        - "mock/dictionary/dictionary2.json"
