openapi: 3.0.3
info:
  title: Settings
  version: '200'
  description: 'Интеграция между ExecutorVocie и АВ IVR для получения настроек'
paths:
  /v1/settings:
    post:
      operationId: getSettings
      summary: Получить полную конфигурацию и реестр функций для сессии GigaVoice
      description: >
        Принимает конфигурацию агента, настройки сессии GigaVoice и информацию о ЕФС.
        Возвращает полные, рассчитанные с учетом контекста, настройки для работы GigaVoice
        и реестр доступных функций с указанием систем-исполнителей.
      parameters:
        - name: UFS-SESSION
          in: header
          description: Идентификатор ЕФС сессии
          required: true
          schema:
            type: string
        - name: UFS-TOKEN
          in: header
          description: Токен ЕФС сессии
          required: true
          schema:
            type: string
      requestBody:
        description: Объекты Configuration, Settings и SessionInfo для получения актуальных настроек.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration:
                  $ref: '#/components/schemas/Configuration'
                settings:
                  $ref: '#/components/schemas/Settings'
                session_info:
                  $ref: '#/components/schemas/SessionInfo'
              required:
                - configuration
                - settings
                - session_info
      responses:
        '200':
          description: Успешный ответ, содержащий полные настройки и реестр функций для сессии.
          content:
            application/json:
              schema:
                type: object
                properties:
                  settings:
                    $ref: '#/components/schemas/Settings'
                  function_registry:
                    $ref: '#/components/schemas/FunctionRegistry'
        '400':
          description: Неверный формат запроса или некорректные данные.
        '500':
          description: Внутренняя ошибка сервера. Попробуйте повторить запрос позже.

  /v1/function-call:
    post:
      operationId: executeFunctionCall
      summary: Вызвать функцию на стороне АВ IVR
      description: >
        Принимает конфигурацию агента, информацию о сессии и объект вызова функции.
        Передает вызов функции на исполнение в АВ IVR и возвращает результат выполнения.
      parameters:
        - name: UFS-SESSION
          in: header
          description: Идентификатор ЕФС сессии
          required: true
          schema:
            type: string
        - name: UFS-TOKEN
          in: header
          description: Токен ЕФС сессии
          required: true
          schema:
            type: string
      requestBody:
        description: Конфигурация агента, информация о сессии и вызов функции для исполнения в АВ IVR.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration:
                  $ref: '#/components/schemas/Configuration'
                session_info:
                  $ref: '#/components/schemas/SessionInfo'
                function_call:
                  $ref: '#/components/schemas/FunctionCall'
              required:
                - configuration
                - session_info
                - function_call
      responses:
        '200':
          description: Успешный ответ с результатом выполнения функции от АВ IVR.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResult'
        '400':
          description: Неверный формат запроса, некорректные данные или ошибка в вызове функции.
        '500':
          description: Внутренняя ошибка сервера АВ IVР или ExecutorVoice. Попробуйте повторить запрос позже.

components:
  schemas:
    Configuration:
      type: object
      description: Конфигурация агента для запроса настроек.
      properties:
        name:
          type: string
          description: fpi-name агента
        type:
          type: string
          description: Тип агента (платформенный, доменный, продуктовый)
        functionalSubsystemCi:
          type: string
          description: КЭ Агента (модуля)
        description:
          type: string
          description: "Дефолтное описание агента. См. на 'descriptionBySessionParams'"
        version:
          type: string
          description: Версия агента. Можно передавать любое значение
        ufsServicesAvailable:
          type: boolean
          description: |
            Возможность получения cookie ЕФС (x_meta.session_info).
            В случае значения false session_info не передается.
          default: false
        availableToolRefs:
          type: array
          description: Массив доступных инструментов. Записываются externalId инструментов (tool)
          items:
            type: string
        availableChannels:
          type: array
          description: Массив доступных каналов ЕФС (MOB_BANK, INVESTOR, SBERKIDS и т.д.)
          items:
            type: string
        availableAgentRefs:
          type: array
          description: Массив доступных агентов. Эти агенты попадают в neighbours_agent_meta в рассчитанной конфигурации. Записываются externalId агентов
          items:
            type: string
        availableToggles:
          type: array
          description: Массив доступных тогглов
          items:
            type: string
        availableEntryPoints:
          type: array
          description: Массив доступных контекстуальных точек входа
          items:
            type: string
        descriptionBySessionParams:
          type: string
          description: Описание для определенной сессии ЦА.
        canAccessUserInfo:
          type: boolean
          description: |
            Новое требование от УЭК
            Возможность получения блока x_meta.user_info из Профиля ФЛ от интеграционного слоя.
            ФИО, дата рождения, пол по SberACL. В значении true блок будет передаваться.
            По-умолчанию false.
            Епк передается при любом значении параметра.
          default: false
        initiativeCode:
          type: string
          description: Номер инициативы в пространстве SHIP. Заполняется номером задачи. Пример - SHIP-123
      required:
        - name
        - type
        - functionalSubsystemCi
        - version
        - initiativeCode

    Settings:
      type: object
      description: Схема для передачи списка настроек поступающих на вход в GigaVoice
      properties:
        mode:
          type: string
          description: Режим работы
        output_modalities:
          type: string
          description: Определяет формат ответа ассистента
        voice_call_id:
          type: string
          description: Уникальный идентификатор звонка в GigaVoice в формате UUID.
        gigachat:
          type: object
          description: Настройки модели
          properties:
            model:
              type: string
              description: Алиас модели
            temperature:
              type: number
              description: Температура выборки значения > 0
            top_p:
              type: number
              minimum: 0
              maximum: 1
              description: Вероятностная масса, кот. нужна для учета результатов токенов. Значения от 0 до 1
            repetition_penalty:
              type: number
              description: Количество повторений слов. Допустимое значение > 0
            profanity_check:
              type: boolean
              description: Включение фильтрации провокационного контента
            filters_settings:
              type: object
              description: Настройки фильтра
              properties:
                request_content:
                  type: object
                  description: Проверка пользовательского запроса
                  properties:
                    neuro:
                      type: boolean
                    blacklist:
                      type: boolean
                    whitelist:
                      type: boolean
                response_content:
                  type: object
                  description: Проверка ответа модели
                  properties:
                    blacklist:
                      type: boolean
            functions:
              type: object
              description: Массив описаний функций
              properties:
                name:
                  type: string
                description:
                  type: string
                parameters:
                  type: string
                few_shot_examples:
                  type: object
                  properties:
                    request:
                      type: string
                    params:
                      type: object
                      properties:
                        pairs:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
                return_parameters:
                  type: string
            function_registry:
              type: object
              description: Параметры запроса для function registry service
              properties:
                profile:
                  type: string
                  description: Профиль пользователя, по которому нужно получить функции
                labels:
                  type: array
                  items: {}
                ab_flags:
                  type: string
                  description: Параметры А/Б-тестирования для проведения А/Б-тестов. Строка с валидной json структурой внутри
            update_interval:
              type: number
        audio:
          type: object
          description: Настройки звука
          properties:
            input:
              type: object
              properties:
                model:
                  type: string
                  description: Модель ASR.
                audio_encoding:
                  type: string
                  description: Формат входного аудио (для распознавания)
                sample_rate:
                  type: number
                  minimum: 8000
                  maximum: 96000
                  description: Частота дискретизации
                silence_phrases:
                  type: array
                  description: Список фраз, одну из которых необходимо озвучить, если пользователь молчит
                  items:
                    type: string
                silence_phrases_timeout:
                  type: number
                  description: Время молчания (без речи) после которого GigaVoice необходимо озвучить фразу (silenсe_phrases).
                silence_timeout:
                  type: number
                  description: Время молчания (без речи) после которого GigaVoice необходимо закрыть соединение duration
                stop_phrases:
                  type: array
                  description: Список фраз остановки проигрывания ответа
                  items:
                    type: string
                ignore_phrases:
                  type: array
                  description: Список фраз, которые необходимо игнорировать от пользователя в момент проигрывания ему ответа модели
                  items:
                    type: string
            output:
              type: object
              properties:
                voice:
                  type: string
                  description: Имя голоса из TTS
                audio_encoding:
                  type: string
                  description: Формат выходного аудио (для синтеза речи)
        context:
          type: object
          description: Стартовый контекст
          properties:
            messages:
              type: object
              description: Массив сообщений
              properties:
                role:
                  type: string
                  description: Роль
                content:
                  type: string
                  description: Содержимое сообщения
                attachments:
                  type: array
                  description: Идентификаторы предзагруженных ранее в GigaChat файлов
                  items:
                    type: string
                function_call:
                  type: object
                  description: Вызов функции с role = assistant
                  properties:
                    name:
                      type: string
                    arguments:
                      type: string
                function_name:
                  type: string
                  description: Имя функции с role = function
                functions_state_id:
                  type: string
                  description: Идентификатор
              required:
                - role
                - content
          required:
            - messages
        disable_vad:
          type: boolean
          description: Выключает VAD, встроенный в GigaVoice
        enable_transcribe_input:
          type: boolean
          description: Транскрибация пользовательского голосового ввода
        flags:
          type: array
          description: Флаги
          items:
            type: string
        enable_denoiser:
          type: boolean
          description: управлять включением шумоподавлением
        first_speaker:
          type: object
          description: Информация о том, кто первый должен начинать взаимодействие
          properties:
            type:
              type: string
              description: Тип первого спикера
            lock_first_in:
              type: boolean
              description: Блокировка первой реплики от перебиваний.
        enable_prefetch:
          type: boolean
          description: Информация о сработке префетча
        enable_person_identity:
          type: boolean
          description: Информация о поле/возрасте
        enable_whisper:
          type: boolean
          description: Информация о шепоте
        enabled_emotion:
          type: boolean
          description: Информация об эмоциях
      required:
        - voice_call_id
        - audio

    SessionInfo:
      type: object
      description: Информация о сессии ЕФС
      properties:
        ufs_host:
          type: string
          description: Хост ЕФС связанный с сессией клиента
          example: "http://nginx-and-ift-b1.testonline.sberbank.ru"
      required:
        - ufs_host

    FunctionRegistry:
      type: object
      description: Схема для фиксирования списка функций и соответствующих систем-исполнителей
      properties:
        functions:
          type: array
          description: Список функций
          items:
            type: object
            properties:
              name:
                type: string
                description: Название функции
              performer:
                type: string
                description: Система-исполнитель функции
            required:
              - performer
              - name
            additionalProperties: false
      required:
        - functions
      additionalProperties: false

    # Новые схемы для второго endpoint
    FunctionCall:
      type: object
      description: Схема для вызова функции на стороне АВ IVR
      properties:
        function_call:
          type: object
          description: Объект вызова функции
          properties:
            name:
              type: string
              description: Наименование функции
            arguments:
              type: object
              description: Аргументы функции. Содержат в себе описание в формате словаря
          required:
            - arguments
            - name
        timestamp:
          type: number
          description: Время генерации в unix time
      required:
        - function_call
        - timestamp
      additionalProperties: false

    FunctionResult:
      type: object
      description: Схема ответа на вызов функции от АВ IVR
      properties:
        result:
          type: object
          description: Результат выполнения функции
          properties:
            content:
              type: string
              description: Содержимое выполнения функции. Должен содержать валидный json
            function_name:
              type: string
              description: Имя функции
          required:
            - content
      required:
        - result
      additionalProperties: false