# Параметры istio
@fpi-name@.ose.istio.control-plane-project=!${global.multiClusters.openshiftControlPlaneSSM}
@fpi-name@.ose.istio.control-plane-istiod-service=${global.multiClusters.openshiftControlPlaneIstiodService}

# Egress
@fpi-name@.ose.istio.egress.common.internal-port=${global.ose.platform.egress.http.port}

@fpi-name@.ose.istio.egress.common.nlb_mm-host=${global.default.nlb_mm.host|}
@fpi-name@.ose.istio.egress.common.nlb_mm-port=${global.default.nlb_mm.port|}

@fpi-name@.ose.istio.egress.se.tcp.kafkaPort.number=${global.platform.ose.kafka.ports}

@fpi-name@.ose.istio.egress.deployment.spec.template.spec.containers.resources.requests.cpu=1000m
@fpi-name@.ose.istio.egress.deployment.spec.template.spec.containers.resources.requests.memory=300Mi
@fpi-name@.ose.istio.egress.deployment.spec.template.spec.containers.resources.limits.cpu=1000m
@fpi-name@.ose.istio.egress.deployment.spec.template.spec.containers.resources.limits.memory=300Mi
## Количество реплик. Обязано быть не меньше 2
@fpi-name@.ose.istio.egress.deployment.spec.replicas=7

@fpi-name@.ose.istio.egress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
@fpi-name@.ose.istio.egress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}
@fpi-name@.ose.istio.egress.deployment.spec.template.spec.terminationGracePeriodSeconds=60

# Ingress
@fpi-name@.ose.istio.ingress.deployment.spec.template.spec.containers.resources.requests.cpu=1000m
@fpi-name@.ose.istio.ingress.deployment.spec.template.spec.containers.resources.requests.memory=400Mi
@fpi-name@.ose.istio.ingress.deployment.spec.template.spec.containers.resources.limits.cpu=1000m
@fpi-name@.ose.istio.ingress.deployment.spec.template.spec.containers.resources.limits.memory=400Mi
## Количество реплик. Обязано быть не меньше 2
@fpi-name@.ose.istio.ingress.deployment.spec.replicas=13

@fpi-name@.ose.istio.ingress.route.spec.host.@config-fp-name1@.appFQDN=@config-fp-name1@-${distrib.release.version}-${global.multiClusters.openshiftNewRoute}

@fpi-name@.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.baseEjectionTime=30s
@fpi-name@.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.consecutive5xxErrors=5
@fpi-name@.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.interval=10s
@fpi-name@.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.maxEjectionPercent=10

@fpi-name@.ose.istio.ingress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
@fpi-name@.ose.istio.ingress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}
@fpi-name@.ose.istio.ingress.deployment.spec.template.spec.terminationGracePeriodSeconds=60

@fpi-name@.ose.istio.ingress.envoy_filter.regex_match.client.cn=${global.ufs.istio.ingress.envoy_filter.regex_match.client.cn}
