# Журналирование
ufs-logger.kafka.bootstrap.servers=${global.platform.logger.kafka.bootstrap.servers}
ufs-logger.kafka.compression.type=${global.platform.logging.kafka.compression}
ufs-logger.kafka.max.request.size=${global.platform.logger.kafka.max.request.size}
ufs-logger.kafka.security.protocol=${global.platform.logger.kafka.security.protocol}
ufs-logger.kafka.ssl.enabled.protocols=${global.platform.kafka.ssl.enabled.protocols}
ufs-logger.kafka.topic=${global.platform.logger.kafka.topic}
ufs-logger.parameters.url=${global.ose.platform.ufs.baseurl.logger}/ufs-logger-parameters-ng/parameters

# Мониторинг

## Режим PUSH
ufs-monitoring.metrics.micrometer.publish.idle=false
ufs-monitoring.micrometer.push.gateway.enabled=true
ufs-monitoring.micrometer.push.gateway.url=${global.monitoring.micrometer.url}
ufs-monitoring.micrometer.push.gateway.job=${global.monitoring.micrometer.job}

## Режим ENDPOINT
ufs-monitoring.micrometer.endpoint.enabled=false
ufs-monitoring.micrometer.endpoint.ssl.enabled=false

## Фильтрация метрик
ufs-monitoring.micrometer.filters.enabled=true
ufs-monitoring.micrometer.filters.connectUrl=${global.monitoring.micrometer.filters.url}

## Настройки для КМ
ufs-monitoring.settings.enabled=true
ufs-monitoring.settings.connectUrl=${global.monitoring.settings.url}
