# Параметры istio
router-executor.ose.istio.control-plane-project=!${global.multiClusters.openshiftControlPlaneSSM}
router-executor.ose.istio.control-plane-istiod-service=${global.multiClusters.openshiftControlPlaneIstiodService}

# Egress
router-executor.ose.istio.egress.common.internal-port=${global.ose.platform.egress.http.port}
router-executor.ose.istio.egress.common.nlb_mm-host=${global.default.nlb_mm.host|}
router-executor.ose.istio.egress.common.nlb_mm-port=${global.default.nlb_mm.port|}
router-executor.ose.istio.egress.se.tcp.kafkaPort.number=${global.platform.ose.kafka.ports}

router-executor.ose.istio.egress.deployment.spec.template.spec.containers.resources.requests.cpu=!100m
router-executor.ose.istio.egress.deployment.spec.template.spec.containers.resources.requests.memory=!250Mi
router-executor.ose.istio.egress.deployment.spec.template.spec.containers.resources.limits.cpu=!200m
router-executor.ose.istio.egress.deployment.spec.template.spec.containers.resources.limits.memory=!500Mi
## Количество реплик. Обязано быть не меньше 2
router-executor.ose.istio.egress.deployment.spec.replicas=2

router-executor.ose.istio.egress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
router-executor.ose.istio.egress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}
router-executor.ose.istio.egress.deployment.spec.template.spec.terminationGracePeriodSeconds=60

# Ingress
router-executor.ose.istio.ingress.deployment.spec.template.spec.containers.resources.requests.cpu=!230m
router-executor.ose.istio.ingress.deployment.spec.template.spec.containers.resources.requests.memory=!400Mi
router-executor.ose.istio.ingress.deployment.spec.template.spec.containers.resources.limits.cpu=!450m
router-executor.ose.istio.ingress.deployment.spec.template.spec.containers.resources.limits.memory=!800Mi
## Количество реплик. Обязано быть не меньше 2
router-executor.ose.istio.ingress.deployment.spec.replicas=2

router-executor.ose.istio.ingress.route.spec.host.router-executor-router-executor.appFQDN=router-executor-router-executor-${distrib.release.version}-${global.multiClusters.openshiftNewRoute}
router-executor.ose.istio.ingress.route.spec.host.@config-fp-name2@.appFQDN=@config-fp-name2@-${distrib.release.version}-${global.multiClusters.openshiftNewRoute}

router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.baseEjectionTime=30s
router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.consecutive5xxErrors=5
router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.interval=10s
router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.maxEjectionPercent=10

router-executor.ose.istio.ingress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
router-executor.ose.istio.ingress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}
router-executor.ose.istio.ingress.deployment.spec.template.spec.terminationGracePeriodSeconds=60

router-executor.ose.istio.ingress.envoy_filter.regex_match.client.cn=${global.ufs.istio.ingress.envoy_filter.regex_match.client.cn}
