apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: router-executor-router-executor
    platformVersion: R4.3
    platformv.sber.ru/releaseVersion: R4.3
    platformv.sber.ru/config-fp-name: router-executor-router-executor
    platformv.sber.ru/fullReleaseVersion: R4.3.5
  name: router-executor-router-executor-${distrib.release.version}
spec:
  replicas: ${router-executor-router-executor.ose.deployment.spec.replicas}
  revisionHistoryLimit: 2
  selector:
    distrib-version: ${jenkins_env.fp_artifact_version}
    jenkinsDeployId: ${jenkinsDeployId}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: ${router-executor-router-executor.ose.deployment.spec.strategy.rollingParams.intervalSeconds}
      maxSurge: ${router-executor-router-executor.ose.deployment.spec.strategy.rollingParams.maxSurge}
      maxUnavailable: ${router-executor-router-executor.ose.deployment.spec.strategy.rollingParams.maxUnavailable}
      timeoutSeconds: ${router-executor-router-executor.ose.deployment.spec.strategy.rollingParams.timeoutSeconds}
      updatePeriodSeconds: ${router-executor-router-executor.ose.deployment.spec.strategy.rollingParams.updatePeriodSeconds}
    type: Rolling
  triggers:
    - type: ConfigChange
  template:
    metadata:
      labels:
        distrib-version: ${jenkins_env.fp_artifact_version}
        jenkinsDeployId: ${jenkinsDeployId}
        platformVersion: R4.3
        platformv.sber.ru/releaseVersion: R4.3
        platformv.sber.ru/config-fp-name: router-executor-router-executor
        platformv.sber.ru/fullReleaseVersion: R4.3.5
      annotations:
        proxy.istio.io/config: |
          drainDuration: 45s
          holdApplicationUntilProxyStarts: true
          terminationDrainDuration: 45s
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: ${router-executor-router-executor.ose.deployment.metadata.annotations.sidecar.istio.io.proxyCPU}
        sidecar.istio.io/proxyMemory: ${router-executor-router-executor.ose.deployment.metadata.annotations.sidecar.istio.io.proxyMemory}
        sidecar.istio.io/proxyCPULimit: ${router-executor-router-executor.ose.deployment.metadata.annotations.sidecar.istio.io.proxyCPULimit}
        sidecar.istio.io/proxyMemoryLimit: ${router-executor-router-executor.ose.deployment.metadata.annotations.sidecar.istio.io.proxyMemoryLimit}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: platformv.sber.ru/config-fp-name
                      operator: In
                      values:
                        - router-executor-router-executor
                topologyKey: 'kubernetes.io/hostname'
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ${global.ufs.secrets.imagePullSecrets}
      restartPolicy: Always
      securityContext: {}
      serviceAccount: default
      terminationGracePeriodSeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.terminationGracePeriodSeconds}
      volumes:
        - name: router-executor-router-executor-config-cm
          configMap:
            name: router-executor-router-executor-config-cm-${distrib.release.version}
            defaultMode: 256
        - name: client-certs-sberca-secret
          secret:
            secretName: client-certs-sberca.unver
            defaultMode: 256
        - name: tmpdir
          emptyDir: {}
        - name: trust-ca-certs-kv-secret
          secret:
            secretName: trust-ca-certs-kv.unver
            defaultMode: 256
      containers:
        - name: router-executor-router-executor-${distrib.release.version}
          image: ${registry}/ci07909419/ci12008538/router-executor-router-executor@${jenkins_env.fp_image_hash}
          imagePullPolicy: IfNotPresent
          env:
            - name: AUDIT_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: AUDIT_POD
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: ose.namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONF_ITEM_AS
              value: "{{ fpConfig.groupId }}"
            - name: CONF_ITEM_FP
              value: "{{ fpConfig.artifactId }}"
            - name: block.id
              value: "{{ NODE_PATH | default('') }}"
            - name: JAVA_OPTS
              value: ${router-executor-router-executor.ose.configmap.javaArguments}
            - name: NODE_PATH
              value: "{{ NODE_PATH | default('') }}"
            - name: PLATFORM_RUNTIME_ENVIRONMENT
              value: OPENSHIFT
            - name: SERVER_MAX_HTTP_HEADER_SIZE
              value: ${global.server.tomcat.max-http-header-size}
            - name: ufs-logger.masked.field.enabled
              value: "true"
            - name: ufs-logger.shouldReadKeystorePasswordFromFile
              value: "true"
            - name: ufs-logger.shouldReadTruststorePasswordFromFile
              value: "true"
            - name: ufs.sds.client.mode
              value: "{%- set node_type = NODE_TYPE | default('') | upper -%} {%- if node_type == 'SANDBOX' -%} REMOTE_DEV_WITH_NEAR_CACHE {%- else -%} REMOTE_WITH_NEAR_CACHE {%- endif -%}"
            - name: ufs.sds.client.currentReplica
              value: "{{ SHARD_ID + '.' + KONTUR_ID if SHARD_ID is defined and KONTUR_ID is defined else '' }}"
            - name: ufs.sds.client.clusterHealthcheckDisabled
              {% set node_type = NODE_TYPE | default('') | upper -%}
              {% set tenant_code = TENANT_CODE | upper -%}
              value: "{{ node_type == "SANDBOX" and tenant_code != "CORE" }}"
            - name: ufs.tenant.code
              value: "{{ TENANT_CODE }}"
          envFrom:
            - configMapRef:
                name: router-executor-all-conf-${distrib.release.version}
            - configMapRef:
                name: router-executor-router-executor-conf-${distrib.release.version}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.livenessProbe.failureThreshold}
            httpGet:
              path: /dab2c-router-executor/v1/environment/product
              port: 8080
              scheme: HTTP
            initialDelaySeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.livenessProbe.initialDelaySeconds}
            periodSeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.livenessProbe.periodSeconds}
            successThreshold: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.livenessProbe.successThreshold}
            timeoutSeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.livenessProbe.timeoutSeconds}
          readinessProbe:
            failureThreshold: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.readinessProbe.failureThreshold}
            httpGet:
              path: /dab2c-router-executor/v1/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.readinessProbe.initialDelaySeconds}
            periodSeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.readinessProbe.periodSeconds}
            successThreshold: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.readinessProbe.successThreshold}
            timeoutSeconds: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.readinessProbe.timeoutSeconds}
          resources:
            limits:
              cpu: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.resources.limits.cpu}
              memory: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.resources.limits.memory}
            requests:
              cpu: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.resources.requests.cpu}
              memory: ${router-executor-router-executor.ose.deployment.spec.template.spec.containers.router-executor-router-executor.resources.requests.memory}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - name: router-executor-router-executor-config-cm
              mountPath: /tmp/ufsparams/config/
            - name: client-certs-sberca-secret
              readOnly: true
              mountPath: /etc/config/ssl/crt/
            - name: tmpdir
              mountPath: /tmp/
            - name: trust-ca-certs-kv-secret
              readOnly: true
              mountPath: /etc/config/ssl/ca/
