/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.ru.sbrf.cbul.cbul.client.spring.boot.starter)
    api(project(":commons"))
    api(project(":monitoring"))
    api(project(":circuit-breaker"))
    api(project(":annotations"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(project(":test-utils"))
}

description = "cbul-integration"
