<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
        <artifactId>executor-shared</artifactId>
        <version>${revision}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>cbul-integration</artifactId>
    <packaging>jar</packaging>
    <version>${revision}</version>

    <build>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.zip</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <includes>
                    <include>**/*.zip</include>
                </includes>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.zip</exclude>
                </excludes>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <includes>
                    <include>**/*.zip</include>
                </includes>
            </testResource>
        </testResources>
    </build>

    <dependencies>

        <!-- CBUL -->
        <dependency>
            <groupId>ru.sbrf.cbul</groupId>
            <artifactId>cbul-client-spring-boot-starter</artifactId>
        </dependency>

        <!-- Commons -->
        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>commons</artifactId>
        </dependency>

        <!-- Monitoring -->
        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>monitoring</artifactId>
        </dependency>

        <!-- Resilience -->
        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>circuit-breaker</artifactId>
        </dependency>

        <!-- CBUL -->
        <dependency>
            <groupId>ru.sbrf.cbul</groupId>
            <artifactId>cbul-client-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk</artifactId>
        </dependency>

        <!-- Тестирование -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>test-utils</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ru.sbrf.ufs.dab2c.core.executor</groupId>
            <artifactId>annotations</artifactId>
        </dependency>

    </dependencies>

</project>
