apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 60000ms
    haproxy.router.openshift.io/balance: roundrobin
    openshift.io/host.generated: 'true'
    ufs.sberbank.ru/context-path: /dab2c-router-executor/v1
    ufs.sberbank.ru/healthcheckHandler: /dab2c-router-executor/v1/healthcheck
    ufs.sberbank.ru/service-id: ROUTER_EXECUTOR_JAVA_DAB2C:router_executor_java_dab2c_router_executor:v1:${jenkins_env.fp_artifact_version}
    ufs.sberbank.ru/weight: "100"
    ufs.sberbank.ru/artifactId: {{ fpConfig.artifactId }}
  name: ingressgateway-mtls-router-executor-router-executor-unver
  labels:
    app: istio-ingressgateway-router-executor-unver
    blockId: "{{ NODE_PATH | default('') }}"
    chart: gateways
    heritage: Tiller
    istio: ingressgateway-router-executor-unver
    release: istio
    sectorId: {{ TENANT_CODE }}
spec:
  host: ${router-executor.ose.istio.ingress.route.spec.host.router-executor-router-executor.appFQDN}
  to:
    kind: Service
    name: ingressgateway-router-executor-unver
    weight: 100
  port:
    targetPort: https-11443
  tls:
    termination: passthrough
  wildcardPolicy: None
