apiVersion: v1
kind: Service
metadata:
  name: ingressgateway-@fpi-name@-unver
  labels:
    app: istio-ingressgateway-@fpi-name@-unver
    istio: ingressgateway-@fpi-name@-unver
    maistra.io/owner: ${@fpi-name@.ose.istio.control-plane-project}
    release: istio
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15020
      targetPort: 15020
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https-11443
      protocol: TCP
      port: 11443
      targetPort: 11443
  selector:
    app: istio-ingressgateway-@fpi-name@-unver
    istio: ingressgateway-@fpi-name@-unver
    release: istio
  sessionAffinity: None
  type: ClusterIP
