apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/load-balance: 'round_robin'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '180'
    nginx.ingress.kubernetes.io/rewrite-target: /
    ufs.sberbank.ru/context-path: /dab2c-router-executor/v1
    ufs.sberbank.ru/healthcheckHandler: /dab2c-router-executor/v1/healthcheck
    ufs.sberbank.ru/service-id: ROUTER_EXECUTOR_JAVA_DAB2C:router_executor_java_dab2c_router_executor:v1:${jenkins_env.fp_artifact_version}
    ufs.sberbank.ru/weight: "100"
    ufs.sberbank.ru/quota: "3200"
  name: ingressgateway-mtls-router-executor-router-executor-unver
  labels:
    app: istio-ingressgateway-router-executor-unver
    blockId: "{{ NODE_PATH | default('') }}"
    chart: gateways
    heritage: Tiller
    istio: ingressgateway-router-executor-unver
    release: istio
    sectorId: {{ TENANT_CODE }}
spec:
  ingressClassName: nginx
  rules:
    - host: ${router-executor.ose.istio.ingress.route.spec.host.router-executor-router-executor.appFQDN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingressgateway-router-executor-unver
                port:
                  name: https-11443
