apiVersion: v1
kind: Service
metadata:
  name: ingressgateway-router-executor-unver
  labels:
    app: istio-ingressgateway-router-executor-unver
    istio: ingressgateway-router-executor-unver
    maistra.io/owner: ${router-executor.ose.istio.control-plane-project}
    release: istio
spec:
  ports:
    - name: http-status-port
      protocol: TCP
      port: 15020
      targetPort: 15020
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https-11443
      protocol: TCP
      port: 11443
      targetPort: 11443
  selector:
    app: istio-ingressgateway-router-executor-unver
    istio: ingressgateway-router-executor-unver
    release: istio
  sessionAffinity: None
  type: ClusterIP
