apiVersion: v1
kind: Service
metadata:
  name: ingressgateway-@fpi-name@-unver
  labels:
    app: istio-ingressgateway-@fpi-name@-unver
    app.kubernetes.io/component: gateways
    app.kubernetes.io/instance: ${@fpi-name@.ctr.istio.control-plane-project}
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: gateways
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.0.2-3.el8-76
    chart: gateways
    heritage: Tiller
    istio: ingressgateway-@fpi-name@-unver
    maistra.io/owner: ${@fpi-name@.ctr.istio.control-plane-project}
    maistra-version: 2.0.2
    release: istio
spec:
  ports:
    - name: http-status-port
      protocol: TCP
      port: 15020
      targetPort: 15020
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https-11443
      protocol: TCP
      port: 11443
      targetPort: 11443
  selector:
    app: istio-ingressgateway-@fpi-name@-unver
    istio: ingressgateway-@fpi-name@-unver
    release: istio
  sessionAffinity: None
  type: ClusterIP