# CBUL
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-kv.unver
spec:
  data:
    - secretKey: cbulToken
      remoteRef:
        key: cbul.dab2c
        property: cbul.dab2c.token
    - secretKey: cbulCN
      remoteRef:
        key: cbul.dab2c
        property: cbul.dab2c.cn
  refreshInterval: "1h"
  secretStoreRef:
    name: secret-store-block-kv
    kind: SecretStore
  target:
    name: secret-kv.unver
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        cbul.dab2c.token: {% raw %}"{{ .cbulToken }}"{% endraw %}
        cbul.dab2c.cn: {% raw %}"{{ .cbulCN }}"{% endraw %}
