apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ingressgateway-mtls-router-executor-router-executor-unver
spec:
  exportTo:
    - .
  host: router-executor-router-executor-${distrib.release.version}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: UFS-SESSION
          ttl: 0s
    outlierDetection:
      consecutive5xxErrors: ${router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.consecutive5xxErrors}
      baseEjectionTime: ${router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.baseEjectionTime}
      interval: ${router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.interval}
      maxEjectionPercent: ${router-executor.ose.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.maxEjectionPercent}
