applications:
  "router-executor-router-executor":
    config_fp_name: "router-executor-router-executor"
    deploymentUnit: "router_executor_java_dab2c_router_executor"
    sup2configFile: "router_executor_java_dab2c_router_executor.json"

release:
  version: "unver"

apiVersion: 1.0.0

schemasVersion: "R4.3.5"

pipeline-extras:
  deploy-common-configmaps: false
  deploy-common-secrets: false
  filter-istio-se: false
  filter-istio-vs: false

playbooks_default:
  "default": [
    "MIGRATION_FP_CONF", "DRY_RUN",
    "IMPORT_ALL_PARAMS",
    "OPENSHIFT_DEPLOY", "OPENSHIFT_INGRESS_EGRESS_DEPLOY"
  ]
