apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-mtls-@fpi-name@-monm-unver
spec:
  exportTo:
    - .
  host: ${global.monitoring.store.host}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: ${global.monitoring.store.port}
        tls:
          caCertificates: /vault/secrets/ca-chain.pem
          clientCertificate: /vault/secrets/client-cert.pem
          privateKey: /vault/secrets/client-cert.key
          mode: MUTUAL
          sni: ${global.monitoring.store.host}
  workloadSelector:
    matchLabels:
      app: istio-egressgateway-@fpi-name@-unver
      istio: egressgateway-@fpi-name@-unver
