/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://nexus-ci.delta.sbrf.ru/repository/public/")
    }

    maven {
        url = uri("https://nexus-ci.delta.sbrf.ru/repository/maven-lib-int/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("javax.annotation:javax.annotation-api:1.3.2")
    api("com.github.spotbugs:spotbugs-annotations:4.8.5")
    api("org.slf4j:slf4j-log4j12:1.7.36")
    api("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    api("ru.sbrf.ufs.platform:ufs-platform-config-api:7.0.25")
    api("org.springframework:spring-core:5.3.39")
    api("org.springframework:spring-context:5.3.39")
    api("ru.sbrf.ufs.platform:ufs-platform-config-core:7.0.25.5-fix-fh")
    api("org.springframework:spring-beans:5.3.39")
    api("org.springframework.boot:spring-boot-autoconfigure:2.7.18")
    api("ru.sbrf.ufs.platform:ufs-platform-api:7.4.6")
    api("ru.sbrf.ufs.platform:ufs-platform-json-mapper:7.4.5.50")
    testImplementation("org.hamcrest:hamcrest-core:2.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.10.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.0")
    testImplementation("org.junit.platform:junit-platform-commons:1.10.0")
    testImplementation("org.junit.platform:junit-platform-engine:1.10.0")
    testImplementation("org.assertj:assertj-core:3.21.0")
    testImplementation("io.mockk:mockk:1.12.3")
    testImplementation("org.springframework:spring-test:5.3.39")
    testImplementation("org.springframework.boot:spring-boot-test:2.7.18")
    testImplementation("org.springframework.boot:spring-boot-test-autoconfigure:2.7.18")
}

group = "ru.sbrf.ufs.dab2c.core.executor"
version = "1.0.0"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
