apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-api-@fpi-name@-unver
spec:
  exportTo:
    - .
  host: '{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 6443
        tls:
          caCertificates: /vault/secrets/ca-chain.pem
          clientCertificate: /vault/secrets/client-cert.pem
          privateKey: /vault/secrets/client-cert.key
          mode: MUTUAL
          sni: '{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
  workloadSelector:
    matchLabels:
      app: istio-egressgateway-@fpi-name@-unver
