# Корневые сертификаты, транзитивно используемые для подписи сертификатов хостов
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-trust-ca-certs-kv.unver
spec:
  data:
    - secretKey: certFileBase64
      remoteRef:
        key: ssl.ose.istio.keyStore.root.Certs
        property: secretFileBase64
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: secret-store-common-kv
  target:
    name: trust-ca-certs-kv.unver
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        root.crt: {% raw %}"{{ .certFileBase64 | b64dec }}"{% endraw %}
---
# Сертификаты для Ingress
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-server-certs-sberca.unver
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ global.hashicorp.serverSberCARole }}
        additionalData:
          description: 'SberCA server-3y-rsa'
          items:
            - name: common_name
              value: {{ fpConfig.groupId }}-{{ fpConfig.artifactId }}-SERVER
            - name: format
              value: pem
            - name: alt_names
              value: ${@fpi-name@.ose.istio.ingress.route.spec.host.@config-fp-name1@.appFQDN}
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: secret-store-common-sberca
  target:
    name: server-certs-sberca.unver
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        tls.crt: {% raw %}"{{ .certificate }}"{% endraw %}
        tls.key: {% raw %}"{{ .private_key }}"{% endraw %}
---
# Сертификаты для основного контейнера и Egress-а
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-client-certs-sberca.unver
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ global.hashicorp.clientSberCARole }}
        additionalData:
          description: 'SberCA client-3y-rsa'
          items:
            - name: common_name
              value: {{ fpConfig.groupId }}-{{ fpConfig.artifactId }}-CLIENT
            - name: format
              value: pem
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: secret-store-common-sberca
  target:
    name: client-certs-sberca.unver
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        tls.crt: {% raw %}"{{ .certificate }}"{% endraw %}
        tls.key: {% raw %}"{{ .private_key }}"{% endraw %}
---
# Секреты для вытягивания образов в Deployment и DeploymentConfig
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-image-pull-secrets-ad.unver
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: registry_user_cred
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: secret-store-common-ad
  target:
    name: {{ lookup('custom_vars','global.ufs.secrets.imagePullSecrets',default='registry') }}
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths": {"{{ registry }}": {% raw %}{"username": "{{.username}}","password": "{{.current_password}}", "email": "put-whatever-you-want", "auth": "{{ printf "%s:%s" .username .current_password | b64enc }}" }}} {% endraw %}'
