{%- macro extract_host(p) -%}
  {{ p | regex_replace('^https?:\/\/api\.([\w\-.]+)(:\d+)?(\/.+)?$', '\\1') }}
{%- endmacro -%}
# SecretStore для секретов уровня стенда
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-common-kv
spec:
  provider:
    vault:
      namespace: {{ lookup('custom_vars', 'global.hashicorp.opsPathCommon').split('/')[1] }}
      server: ${global.hashicorp.hashiCorpUrl}
      path: ${global.hashicorp.opsPathCommon}
      version: ${global.hashicorp.engine.kv.version}
      auth:
        kubernetes:
          mountPath: k8s/{{ extract_host(vars['global.multiClusters.openshiftCluster']) }}
          role: "auth-role-efsfl"
          serviceAccountRef:
            name: "default"

---
# SecretStore для COMMON хранилища SberCA (PKI)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-common-sberca
spec:
  provider:
    vault:
      namespace: {{ lookup('custom_vars', 'global.hashicorp.opsPathCommonPKI').split('/')[1] }}
      server: ${global.hashicorp.hashiCorpUrl}
      path: ${global.hashicorp.opsPathCommonPKI}
      secretEngineType: "sberca"
      auth:
        kubernetes:
          mountPath: k8s/{{ extract_host(vars['global.multiClusters.openshiftCluster']) }}
          role: "auth-role-efsfl"
          serviceAccountRef:
            name: "default"

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-common-ad
spec:
  provider:
    vault:
      namespace: {{ lookup('custom_vars', 'global.hashicorp.opsPathCommonAD').split('/')[1] }}
      server: ${global.hashicorp.hashiCorpUrl}
      path: ${global.hashicorp.opsPathCommonAD}
      secretEngineType: "ad"
      auth:
        kubernetes:
          mountPath: k8s/{{ extract_host(vars['global.multiClusters.openshiftCluster']) }}
          role: "auth-role-efsfl"
          serviceAccountRef:
            name: "default"
