server:
  servlet:
    context-path: /@server.context.path@

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}
  client:
    downstream:
      address: static://${GRPC_DOWNSTREAM_HOST:localhost}:${GRPC_DOWNSTREAM_PORT:9091}
      negotiation-type: plaintext

logging:
  level:
    root: INFO
