server:
  address: @server.host@
  port: @server.port@
  tomcat:
    threads:
      max: 20
      min-spare: 5
  kafka:
    bootstrap-servers: "tcp://@kafka.host@:@kafka.port@"

stand:
  type: TEST

ufs:
  platform:
    # СУП
    config:
      directory: 'classpath:/mock/sup'
      agent:
        disabled: true
    # Launcher
    launcherstub:
      enabled: true
      enable-rest: true

  # ССД
  sds:
    client:
      mode: LOCAL
      http:
        integration-enabled: true

  # Журналирование
  logger:
    client:
      mode: FRONTEND_LOCAL
      providerFileName: "/mock/logger/logger.properties"

  # Мониторинг
  # См. также pom.xml с включением stubMode
  monitoring:
    client:
      period: 20s
    kafka:
      enabled: false
      ssl: false

  # Аудит
  audit:
    client:
      stub: true
      useQuota: false
