spring:
  webflux:
    base-path: /@server.context.path@
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:PROM}

management:
  server:
    port: 8081  # только для эндпоинтов actuator
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus
      path-mapping:
        prometheus: metrics
    metrics:
      export:
        prometheus:
         enabled: true
