/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.com.jayway.jsonpath.json.path)
    api(libs.org.apache.httpcomponents.httpcore)
    api(libs.ru.sbrf.ufs.platform.environment.spring.boot.starter)
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.ru.sbrf.ufs.platform.httpclient.spring.boot.starter)
}

description = "rest-object-mapper"
