/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    alias(libs.plugins.spring.boot)
}

springBoot {
    mainClass.set("ru.sbrf.ufs.dab2c.core.executor.deployments.router.executor.app.RouterExecutorApplicationEntryPointKt")
}

dependencies {
    api(project(":executor-shared:health-check"))
    api(project(":executor-shared:commons"))
    api(project(":executor-shared:cbul-integration"))
    api(libs.ru.sbrf.ufs.platform.environment.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.ufs.platform.cache.impl)
    api(libs.ru.sbrf.ufs.platform.httpclient.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.ufs.platform.config.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.config.agent.spring.boot.starter)
    api(libs.ru.sbrf.ufs.app.hotreload.hotreload.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.logger.springboot.starter)
    api(libs.ru.sbrf.ufs.monitoring.spring.boot.monitoring.spring.boot.starter)
    api(libs.ru.sbrf.ufs.healthcheck.ufs.healthcheck.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.rest.app.jersey.spring.boot.starter)
    api(libs.com.networknt.json.schema.validator)
    api(project(":executor-shared:monitoring"))
    api(project(":executor-shared:circuit-breaker"))
    api(project(":executor-shared:logging"))
    api(project(":executor-shared:concurrent"))
    api(project(":executor-shared:rest-object-mapper"))
    testImplementation(project(":executor-shared:test-utils"))
}

description = "router-executor"
