/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":health-check"))
    api(project(":commons"))
    api(project(":cbul-integration"))
    api(libs.ru.sbrf.ufs.platform.environment.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.ufs.platform.cache.impl)
    api(libs.ru.sbrf.ufs.platform.httpclient.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.ufs.platform.config.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.config.agent.spring.boot.starter)
    api(libs.ru.sbrf.ufs.app.hotreload.hotreload.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.logger.springboot.starter)
    api(libs.ru.sbrf.ufs.monitoring.spring.boot.monitoring.spring.boot.starter)
    api(libs.ru.sbrf.ufs.healthcheck.ufs.healthcheck.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.rest.app.jersey.spring.boot.starter)
    api(libs.com.networknt.json.schema.validator)
    api(project(":monitoring"))
    api(project(":circuit-breaker"))
    api(project(":logging"))
    api(project(":concurrent"))
    api(project(":rest-object-mapper"))
    testImplementation(project(":test-utils"))
}

description = "router-executor"
