# Параметры istio
@fpi-name@.ctr.istio.control-plane-project=!${global.multiClusters.openshiftControlPlaneSSM}
@fpi-name@.ctr.istio.control-plane-istiod-service=${global.multiClusters.openshiftControlPlaneIstiodService}

# Egress
@fpi-name@.ctr.istio.egress.common.internal-port=${global.ose.platform.egress.http.port}
@fpi-name@.ctr.istio.egress.common.nlb_mm-host=${global.default.nlb_mm.host|}
@fpi-name@.ctr.istio.egress.common.nlb_mm-port=${global.default.nlb_mm.port|}
@fpi-name@.ctr.istio.egress.se.tcp.kafka.port=9093
@fpi-name@.ctr.istio.egress.se.http.iag-mm.host=${global.default.nlb_mm.host}
@fpi-name@.ctr.istio.egress.se.http.iag-mm.port=${global.default.nlb_mm.port}

@fpi-name@.ctr.istio.egress.deployment.spec.template.spec.terminationGracePeriodSeconds=60
@fpi-name@.ctr.istio.egress.deployment.spec.template.spec.containers.resources.limits.cpu=!200m
@fpi-name@.ctr.istio.egress.deployment.spec.template.spec.containers.resources.limits.memory=!512Mi
@fpi-name@.ctr.istio.egress.deployment.spec.template.spec.containers.resources.requests.cpu=!100m
@fpi-name@.ctr.istio.egress.deployment.spec.template.spec.containers.resources.requests.memory=!256Mi
@fpi-name@.ctr.istio.egress.deployment.spec.replicas=2

@fpi-name@.ctr.istio.egress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
@fpi-name@.ctr.istio.egress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}

# Ingress
@fpi-name@.ctr.istio.ingress.deployment.spec.template.spec.terminationGracePeriodSeconds=60
@fpi-name@.ctr.istio.ingress.deployment.spec.template.spec.containers.resources.limits.cpu=!450m
@fpi-name@.ctr.istio.ingress.deployment.spec.template.spec.containers.resources.limits.memory=!800Mi
@fpi-name@.ctr.istio.ingress.deployment.spec.template.spec.containers.resources.requests.cpu=!350m
@fpi-name@.ctr.istio.ingress.deployment.spec.template.spec.containers.resources.requests.memory=!600Mi
@fpi-name@.ctr.istio.ingress.deployment.spec.replicas=2

@fpi-name@.ctr.istio.ingress.route.spec.host.@fpi-name@.appFQDN=@fpi-name@-${distrib.release.version}-${global.multiClusters.openshiftNewRoute}
@fpi-name@.ctr.istio.ingress.route.spec.host.@fpi-name@.appFQDN2=@as-conf-item.lowercase@-@fpi-name@-${global.multiClusters.openshiftNewRoute}
@fpi-name@.ctr.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.baseEjectionTime=30s
@fpi-name@.ctr.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.consecutive5xxErrors=5
@fpi-name@.ctr.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.interval=10s
@fpi-name@.ctr.istio.ingress.dsr.spec.trafficPolicy.outlierDetection.maxEjectionPercent=10

@fpi-name@.ctr.istio.ingress.deployment.spec.strategy.rollingUpdate.maxUnavailable=${global.ufs.strategy.maxUnavailable}
@fpi-name@.ctr.istio.ingress.deployment.spec.strategy.rollingUpdate.maxSurge=${global.ufs.strategy.maxSurge}

@fpi-name@.ctr.istio.ingress.envoy_filter.regex_match.client.cn=${global.ufs.istio.ingress.envoy_filter.regex_match.client.cn}

# DA Configurator
@fpi-name@.ctr.istio.egress.se.http.daconf.host={{ (lookup('custom_vars','global.import.service.da_conf.url') | regex_replace("^https?://", "")).split("/")[0] }}
@fpi-name@.ctr.istio.egress.se.http.daconf.port=443

# DA Shes
@fpi-name@.ctr.istio.egress.se.http.dashes.host=CHANGE_ME_HOST
@fpi-name@.ctr.istio.egress.se.http.dashes.port=CHANGE_ME_PORT
