apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egressgateway-federate-router-executor-unver
spec:
  exportTo:
    - .
  hosts:
    - 'metrics.{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
  gateways:
    - mesh
    - egressgateway-federate-router-executor-unver
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: egressgateway-federate-router-executor-unver
            port:
              number: 2001
    - match:
        - gateways:
            - egressgateway-federate-router-executor-unver
          port: 2001
      route:
        - destination:
            host: 'metrics.{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
            port:
              number: 8481
