apiVersion: v1
kind: Service
metadata:
  name: egressgateway-federate-router-executor-unver
  labels:
    app: egressgateway-router-executor-unver
  namespace: ${global.multiClusters.openshiftProjectName}
spec:
  ports:
    - name: http-2001
      protocol: TCP
      port: 2001
      targetPort: 2001
  selector:
    app: istio-egressgateway-router-executor-unver
