apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allow-metrics-scraping
spec:
  addresses:
    - 29.64.0.0/16
  exportTo:
    - .
  hosts:
    - vmagent-metrics.local
  ports:
    - name: tcp-8000
      number: 8000
      protocol: TCP
    - name: tcp-2020
      number: 2020
      protocol: TCP
  resolution: NONE