apiVersion: v1
kind: Service
metadata:
  name: egressgateway-router-executor-unver
  labels:
    app: istio-egressgateway-router-executor-unver
    istio: egressgateway-router-executor-unver
    maistra.io/owner: ${router-executor.ose.istio.control-plane-project}
    release: istio
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-ose
      protocol: TCP
      port: ${router-executor.ose.istio.egress.common.internal-port}
      targetPort: ${router-executor.ose.istio.egress.common.internal-port}
    - name: https
      protocol: TCP
      port: 443
      targetPort: ${router-executor.ose.istio.egress.common.nlb_mm-port}
    - name: http-tls
      protocol: TCP
      port: 13443
      targetPort: 13443
    - name: http-monitoring
      protocol: TCP
      port: ${global.monitoring.store.port}
      targetPort: ${global.monitoring.store.port}
  selector:
    app: istio-egressgateway-router-executor-unver
  sessionAffinity: None
  type: ClusterIP
