apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-agent
data:
  scrape.yaml: |
    global:
      scrape_interval: 1m
    scrape_configs:
      - job_name: 'dab2c-app-{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}'
        metrics_path: /actuator/metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - '{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}'
            api_server: 'http://api.{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              insecure_skip_verify: true
        relabel_configs:
          - source_labels: []
            target_label: __metrics_path__
            replacement: /actuator/metrics
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
          - source_labels: [__meta_kubernetes_pod_label_distribVersion]
            target_label: distrib_version
          - source_labels: [__meta_kubernetes_pod_label_subsystem]
            target_label: subsystem
          - source_labels: [__meta_kubernetes_pod_label_appCI]
            target_label: ci
          - source_labels: [__meta_kubernetes_pod_label_block]
            target_label: block
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service_name
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '8000'
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
            target_label: __address__
            separator: ":"
            replacement: "$1$2"
            action: replace
      - job_name: 'dab2c-efs-federate-{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}'
        metrics_path: /federate
        params:
          'match[]':
            - '{__name__=~"container_.+", namespace="{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}", cluster="{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}"}'
            - '{__name__=~"kube_pod_.+", namespace="{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}", cluster="{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}"}'
        static_configs:
          - targets:
              - 'metrics.{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
        scheme: http
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
      - job_name: 'dab2c-fluentbit-{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}'
        metrics_path: /api/v2/metrics/prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - '{{ lookup("custom_vars", "global.multiClusters.openshiftProjectName") }}'
            api_server: 'http://api.{{ lookup("custom_vars", "global.multiClusters.openshiftCluster") | regex_replace("^https?://", "") | regex_replace("^api\\.", "") | regex_replace(":[^/:]*", "") | regex_replace("/[^/]*$", "") }}'
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              insecure_skip_verify: true
        relabel_configs:
          - source_labels: []
            target_label: __metrics_path__
            replacement: /api/v2/metrics/prometheus
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
          - source_labels: [__meta_kubernetes_pod_label_distribVersion]
            target_label: distrib_version
          - source_labels: [__meta_kubernetes_pod_label_subsystem]
            target_label: subsystem
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '2020'
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number]
            target_label: __address__
            separator: ":"
            replacement: "$1$2"
            action: replace
