/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.ru.sbrf.ufs.platform.environment.spring.boot.starter)
    api(libs.ru.sbrf.ufs.platform.logger.springboot.starter)
    api(project(":commons"))
    api(libs.io.github.resilience4j.resilience4j.circuitbreaker)
    testImplementation(project(":test-utils"))
}

description = "circuit-breaker"
